-- schema.sql — Skema Database Pantau Server
-- AUTOGENERATED dari server/models.py (SQLAlchemy create_all -> mysqldump).
-- Jangan diedit manual. Untuk database baru cukup:
--   mysql -uroot -e "CREATE DATABASE pantau_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
--   mysql -uroot pantau_db < schema.sql
--   mysql -uroot -e "CREATE USER 'pantau_db'@'127.0.0.1' IDENTIFIED BY '<pass>'; GRANT ALL ON pantau_db.* TO 'pantau_db'@'127.0.0.1';"

/*M!999999\- enable the sandbox mode */ 

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `audit_logs`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `audit_logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(100) NOT NULL,
  `action` varchar(50) NOT NULL,
  `target` varchar(255) DEFAULT NULL,
  `result` varchar(500) DEFAULT NULL,
  `meta` text DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_audit_username` (`username`),
  KEY `idx_audit_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `commands`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `commands` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `server_id` int(10) unsigned NOT NULL,
  `service_id` int(11) DEFAULT NULL,
  `action` varchar(20) NOT NULL,
  `params` text DEFAULT NULL,
  `issued_by` varchar(100) DEFAULT NULL,
  `status` enum('pending','executing','success','failed') NOT NULL,
  `result` text DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `executed_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `server_id` (`server_id`),
  KEY `service_id` (`service_id`),
  KEY `idx_commands_status` (`status`),
  CONSTRAINT `commands_ibfk_1` FOREIGN KEY (`server_id`) REFERENCES `servers` (`id`) ON DELETE CASCADE,
  CONSTRAINT `commands_ibfk_2` FOREIGN KEY (`service_id`) REFERENCES `services` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `log_requests`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `log_requests` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `server_id` int(10) unsigned NOT NULL,
  `unit` varchar(100) NOT NULL,
  `lines` int(11) NOT NULL,
  `detail` varchar(128) DEFAULT NULL,
  `status` enum('pending','executing','success','failed') NOT NULL,
  `result` mediumtext DEFAULT NULL,
  `input_data` varchar(500) DEFAULT NULL,
  `input_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_log_requests_server_status` (`server_id`,`status`,`created_at`),
  CONSTRAINT `log_requests_ibfk_1` FOREIGN KEY (`server_id`) REFERENCES `servers` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `login_attempts`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `login_attempts` (
  `ip_address` varchar(45) NOT NULL,
  `fails` int(11) NOT NULL,
  `lock_until` datetime DEFAULT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`ip_address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `metrics`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `metrics` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `service_id` int(11) NOT NULL,
  `timestamp` datetime DEFAULT NULL,
  `status` enum('up','down') NOT NULL,
  `active_connections` int(11) NOT NULL,
  `response_time_ms` int(11) DEFAULT NULL,
  `health_message` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_metrics_service_ts` (`service_id`,`timestamp`),
  CONSTRAINT `metrics_ibfk_1` FOREIGN KEY (`service_id`) REFERENCES `services` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `server_extras`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `server_extras` (
  `server_id` int(10) unsigned NOT NULL,
  `kernel` varchar(100) DEFAULT NULL,
  `os_label` varchar(120) DEFAULT NULL,
  `arch` varchar(24) DEFAULT NULL,
  `agent_version` varchar(16) DEFAULT NULL,
  `units` text DEFAULT NULL,
  `accounts` text DEFAULT NULL,
  `apt_upgradable` int(11) DEFAULT NULL,
  `apt_last_update` datetime DEFAULT NULL,
  `apt_packages` text DEFAULT NULL,
  `security` text DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`server_id`),
  CONSTRAINT `server_extras_ibfk_1` FOREIGN KEY (`server_id`) REFERENCES `servers` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `server_problems`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `server_problems` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `server_id` int(10) unsigned NOT NULL,
  `key` varchar(160) NOT NULL,
  `severity` varchar(10) NOT NULL,
  `message` varchar(255) NOT NULL,
  `tip` varchar(500) DEFAULT NULL,
  `started_at` datetime NOT NULL,
  `resolved_at` datetime DEFAULT NULL,
  `updated_at` datetime NOT NULL,
  `acknowledged_at` datetime DEFAULT NULL,
  `acknowledged_by` varchar(100) DEFAULT NULL,
  `last_active_at` datetime DEFAULT NULL,
  `resolved_note` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_server_problems_server_id` (`server_id`),
  KEY `idx_problems_open` (`server_id`,`resolved_at`),
  CONSTRAINT `server_problems_ibfk_1` FOREIGN KEY (`server_id`) REFERENCES `servers` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `servers`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `servers` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `hostname` varchar(255) NOT NULL,
  `ip_address` varchar(45) NOT NULL,
  `api_key` varchar(80) NOT NULL,
  `is_active` smallint(6) NOT NULL,
  `last_seen` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `api_key` (`api_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `services`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `services` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `server_id` int(10) unsigned NOT NULL,
  `service_name` varchar(100) NOT NULL,
  `port` int(11) NOT NULL,
  `process_name` varchar(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_server_service` (`server_id`,`service_name`),
  CONSTRAINT `services_ibfk_1` FOREIGN KEY (`server_id`) REFERENCES `servers` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `sessions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `sessions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sid` varchar(64) NOT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  `expires_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `sid` (`sid`),
  KEY `ix_sessions_expires_at` (`expires_at`),
  KEY `ix_sessions_user_id` (`user_id`),
  CONSTRAINT `sessions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `sys_snapshots`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `sys_snapshots` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `server_id` int(10) unsigned NOT NULL,
  `timestamp` datetime DEFAULT NULL,
  `cpu` float NOT NULL,
  `load1` float DEFAULT NULL,
  `load5` float DEFAULT NULL,
  `load15` float DEFAULT NULL,
  `mem_total` bigint(20) NOT NULL,
  `mem_used` bigint(20) NOT NULL,
  `mem_avail` bigint(20) NOT NULL,
  `swap_total` bigint(20) NOT NULL,
  `swap_used` bigint(20) NOT NULL,
  `procs` int(11) DEFAULT NULL,
  `uptime_secs` bigint(20) DEFAULT NULL,
  `disks` text DEFAULT NULL,
  `net` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_sys_snapshots_server_ts` (`server_id`,`timestamp`),
  CONSTRAINT `sys_snapshots_ibfk_1` FOREIGN KEY (`server_id`) REFERENCES `servers` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `sys_snapshots_hourly`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `sys_snapshots_hourly` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `server_id` int(10) unsigned NOT NULL,
  `bucket` datetime NOT NULL,
  `samples` int(11) NOT NULL,
  `cpu_avg` float NOT NULL,
  `cpu_max` float NOT NULL,
  `load1_avg` float DEFAULT NULL,
  `load5_avg` float DEFAULT NULL,
  `load15_avg` float DEFAULT NULL,
  `mem_total` bigint(20) NOT NULL,
  `mem_used_avg` bigint(20) NOT NULL,
  `mem_avail_avg` bigint(20) NOT NULL,
  `swap_total` bigint(20) NOT NULL,
  `swap_used_avg` bigint(20) NOT NULL,
  `procs_avg` int(11) DEFAULT NULL,
  `disk_max_pct` float DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_hour_server_bucket` (`server_id`,`bucket`),
  CONSTRAINT `sys_snapshots_hourly_ibfk_1` FOREIGN KEY (`server_id`) REFERENCES `servers` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `users`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(100) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `role` enum('admin','viewer') NOT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
SET FOREIGN_KEY_CHECKS=1;
