-- ============================================================
-- CATAHAN UNTUK SEED / TEST DATA
-- ============================================================
-- Dashboard TIDAK menyimpan API key mentah: kolom servers.api_key berisi
-- "sha256:<hex64>" (hash). Karena itu API key HANYA boleh dibuat lewat
-- Dashboard (menu Server -> Tambah Server). Jangan inset key mentah lewat SQL.
--
-- Untuk membuat server contoh lewat SQL (hanya untuk uji coba lokal):
--
-- 1) Generate hash yang sesuai SHA256 64 hex:
--      printf 'abcdef...64hex...\n' | sha256sum
--    lalu simpan dengan awalan "sha256:"
--
-- 2) INSERT server + layanan contoh:
--   SET @raw = '0000000000000000000000000000000000000000000000000000000000000001';
--   SET @hash = CONCAT('sha256:', SHA2(@raw, 256));
--   INSERT INTO servers (hostname, ip_address, api_key, is_active)
--     VALUES ('web-prod-01', '192.168.1.10', @hash, 1);
--   INSERT INTO services (server_id, service_name, port, process_name) VALUES
--     (LAST_INSERT_ID(), 'nginx', 80,   'nginx'),
--     (LAST_INSERT_ID(), 'pgsql', 5432, 'postgres');
--
-- 3) Untuk menghubungkan agen ke server contoh tsb, agen harus dikonfigurasi
--    dengan @raw (bukan hash) di /etc/pantau/config.json -> api_key.
--
-- Lihat juga: database/schema.sql dan package/install.sh.
-- ============================================================